const fs = require('fs');

const zh = {
  common: {
    language: '语言',
    loading: '加载中...',
    login: '登录',
    logout: '退出登录',
    save: '保存',
    cancel: '取消',
    submit: '提交',
    confirm: '确认',
    delete: '删除',
    edit: '编辑',
    view: '查看',
    create: '创建',
    update: '更新',
    search: '搜索',
    filter: '筛选',
    settings: '设置',
    back: '返回',
    next: '下一步',
    previous: '上一步',
    close: '关闭',
    open: '打开',
    yes: '是',
    no: '否',
    ok: '确定',
    error: '错误',
    success: '成功',
    warning: '警告',
    info: '信息',
    required: '必填',
    optional: '可选',
    enabled: '已启用',
    disabled: '已禁用',
    active: '活跃',
    inactive: '非活跃',
    name: '名称',
    description: '描述',
    email: '邮箱',
    password: '密码',
    username: '用户名',
    role: '角色',
    status: '状态',
    actions: '操作',
    details: '详情',
    overview: '概览',
    general: '通用',
    advanced: '高级',
    basic: '基础',
    custom: '自定义',
    default: '默认',
    select: '选择',
    choose: '请选择',
    selectOption: '请选择选项',
    noResults: '未找到结果',
    noData: '暂无数据',
    tryAgain: '重试',
    learnMore: '了解更多',
    documentation: '文档',
    version: '版本',
    enterprise: '企业版',
    free: '免费',
    trial: '试用',
    upgrade: '升级',
    premium: '高级版',
    standard: '标准版',
    beta: 'Beta 版',
    alpha: 'Alpha 版',
    stable: '稳定版',
    experimental: '实验性',
    deprecated: '已弃用',
    new: '新增',
    updated: '已更新',
    loadingData: '正在加载数据...',
    noItems: '暂无项目',
    copy: '复制',
    copied: '已复制',
    rename: '重命名',
    duplicate: '复制',
    archive: '归档',
    restore: '恢复',
    remove: '移除',
    add: '添加',
    import: '导入',
    export: '导出',
    download: '下载',
    upload: '上传',
    refresh: '刷新',
    reset: '重置',
    clear: '清除',
    apply: '应用',
    discard: '放弃',
    continue: '继续',
    finish: '完成',
    done: '完成',
    processing: '处理中...',
    pending: '待处理',
    completed: '已完成',
    failed: '失败',
    timeout: '超时',
    retry: '重试',
    skip: '跳过',
    ignore: '忽略',
    confirmDelete: '确定要删除此项吗？',
    confirmAction: '确定要继续吗？',
    unsavedChanges: '您有未保存的更改。确定要离开吗？',
    sessionExpired: '您的会话已过期，请重新登录。',
    unauthorized: '未授权的访问',
    forbidden: '访问被拒绝',
    notFound: '未找到',
    serverError: '服务器错误，请稍后重试。',
    networkError: '网络错误，请检查您的连接。',
  },
  nav: {
    aiGateway: 'AI 网关',
    observability: '可观测性',
    accessControl: '访问控制',
    developerTools: '开发者工具',
    settings: '设置',
    virtualKeys: '虚拟密钥',
    playground: '演练场',
    modelsAndEndpoints: '模型 + 端点',
    agentic: '智能体',
    agents: '智能体',
    workflowRuns: '工作流运行',
    memory: '记忆',
    mcpServers: 'MCP 服务器',
    skills: '技能',
    guardrails: '护栏',
    policies: '策略',
    tools: '工具',
    searchTools: '搜索工具',
    vectorStores: '向量存储',
    toolPolicies: '工具策略',
    usage: '用量',
    costOptimization: '成本优化',
    logs: '日志',
    guardrailsMonitor: '护栏监控',
    teams: '团队',
    projects: '项目',
    internalUsers: '内部用户',
    organizations: '组织',
    accessGroups: '访问组',
    budgets: '预算',
    apiReference: 'API 参考',
    aiHub: 'AI 中心',
    learningResources: '学习资源',
    responseCache: '响应缓存',
    experimental: '实验性',
    prompts: '提示词',
    apiPlayground: 'API 演练场',
    tagManagement: '标签管理',
    oldUsage: '旧版用量',
    routerSettings: '路由设置',
    loggingAndAlerts: '日志与告警',
    adminSettings: '管理员设置',
    costTracking: '成本追踪',
    uiTheme: '界面主题',
  },
  viewSwitcher: {
    aiGateway: 'AI 网关',
    chat: '聊天',
    adminsCanEnableInSettings: '管理员可在设置中启用',
  },
  login: {
    brand: '🚅 LiteLLM',
    title: '登录',
    subtitle: '访问您的 LiteLLM 管理界面。',
    defaultCredentials: '默认凭据',
    defaultCredentialsDesc: '默认情况下，用户名为 {username}，密码为您设置的 LiteLLM Proxy {masterKey}。',
    needHelp: '需要设置界面凭据或 SSO？{link}查看文档{/link}。',
    workerLabel: '工作节点',
    workerPlaceholder: '选择要连接的工作节点',
    usernameLabel: '用户名',
    usernamePlaceholder: '请输入用户名',
    passwordLabel: '密码',
    passwordPlaceholder: '请输入密码',
    loggingIn: '登录中...',
    loginButton: '登录',
    ssoButton: '使用 SSO 登录',
    ssoTooltip: '请先配置 SSO 才能使用 SSO 登录。',
    adminDisabledTitle: '管理界面已禁用',
    adminDisabledDesc: '管理界面已被管理员禁用。如需重新启用，请更新以下环境变量：',
    adminDisabledCode: 'DISABLE_ADMIN_UI=False',
    ssoEnabledTitle: '单点登录 (SSO) 已启用',
    ssoEnabledDesc: 'LiteLLM 加载此页面时不再自动重定向到 SSO 登录流程。如需重新启用自动重定向到 SSO，请在环境配置中设置 {code}AUTO_REDIRECT_UI_LOGIN_TO_SSO=true{/code}。',
    ssoDismiss: '关闭',
  },
  onboarding: {
    brand: '🚅 LiteLLM',
    signUp: '注册',
    signUpDesc: '认领您的用户账户以登录管理界面。',
    resetPassword: '重置密码',
    resetPasswordDesc: '重置您的密码以访问管理界面。',
    ssoTitle: 'SSO',
    ssoDesc: 'SSO 属于企业版功能。',
    getFreeTrial: '获取免费试用',
    emailLabel: '邮箱地址',
    passwordLabel: '密码',
    createPasswordDesc: '为您的账户创建密码',
    newPasswordDesc: '请输入新密码',
    signUpButton: '注册',
    resetPasswordButton: '重置密码',
    loadingInvitation: '正在加载邀请...',
    errorTitle: '加载邀请失败',
    errorDesc: '邀请链接可能无效或已过期。',
    backToLogin: '返回登录',
  },
  breadcrumb: {
    unknownPage: '未知页面',
  },
  ssoEnabledNotice: '单点登录 (SSO) 已启用。LiteLLM 加载此页面时不再自动重定向到 SSO 登录流程。如需重新启用自动重定向到 SSO，请在环境配置中设置 AUTO_REDIRECT_UI_LOGIN_TO_SSO=true。',
};

fs.writeFileSync('src/messages/zh-CN.json', JSON.stringify(zh, null, 2) + '\n');
console.log('zh-CN.json written');